# -*- mode: ruby -*-
# vi: set ft=ruby :
#
Vagrant.configure("2") do |config|
  # https://docs.vagrantup.com.
  # boxes at https://vagrantcloud.com/search.
 
  config.vm.box = "b2-tp2-centos"
  
   # adding a second disk
  CONTROL_NODE_DISK='./disk2.vdi'

  config.vbguest.auto_update = true
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  
  config.vm.define "node1" do |nd1|
     nd1.vm.provider "virtualbox" do |nd|
        nd.memory = "1024"
        nd.name = "node1"
        unless File.exist?(CONTROL_NODE_DISK)
          nd.customize ['createhd', '--filename', CONTROL_NODE_DISK, '--variant', 'Fixed', '--size', 5 * 1024]
         end
         # Attache le disque à la VM
        nd.customize ['storageattach', :id,  '--storagectl', 'IDE', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', CONTROL_NODE_DISK]
    end
    nd1.vm.network "private_network", ip: "192.168.2.21"
    nd1.vm.hostname = "node1.tp2.b2"
    nd1.vm.provision "file", source: "./nginx.conf", destination: "/tmp/nginx.conf"
    nd1.vm.provision "file", source: "./server.crt", destination: "/tmp/server.crt"
    nd1.vm.provision "file", source: "./server.key", destination: "/tmp/server.key"
     # Exécution d'un script au démarrage de la VM
    nd1.vm.provision "shell", path: "script1.sh"
  end 

  config.vm.define "node2" do |nd2|
     nd2.vm.provider "virtualbox" do |nd|
        nd.memory = "512"
        nd.name = "node2"
    end
    nd2.vm.network "private_network", ip: "192.168.2.22"
    nd2.vm.hostname = "node2.tp2.b2"
    nd2.vm.provision "file", source: "./server.crt", destination: "/tmp/server.crt"
    nd2.vm.provision "shell", path: "script3.sh"
  end
  
  # Exécution d'un script au démarrage de la VM
  config.vm.provision "shell", path: "script2.sh"
end
